config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root 'welcome#home'
  get 'welcome/about'



  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #belongs_to :recipe
  #belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  #has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  #has_many :comments, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @recipe_comments = @recipe.comments
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    #@recipe.user = current_user # ADDED BY BINA
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :picture, :user_id, :ingredients, :description, :serving, :language, :preptime, :cooktime, :likes, :notes, :comments)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :language, :password, :avatar, :recipes, :following, :followers, :translated, :points, :menu, :planner, :shoplist)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_area :user_id %>
  </div>

  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.text_area :recipe_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User Id</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.recipe_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User Id:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="#">Globalitious</a>
      by <a href="#">Baichechekei</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", root_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GLOBALICIOUS", root_path, class: "navbar-brand" %> <!-- HTML to ERB -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "About", welcome_about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New user", new_user_path %></li>
            <li><%= link_to "All users", users_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New recipe", new_recipe_path %></li>
            <li><%= link_to "View recipes", recipes_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Find recipe">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">View profile</a></li>
            <li><a href="#">Edit profile</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Globalicious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_area :picture %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :serving %>
    <%= f.number_field :serving %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_area :language %>
  </div>

  <div class="field">
    <%= f.label :preptime %>
    <%= f.number_field :preptime %>
  </div>

  <div class="field">
    <%= f.label :cooktime %>
    <%= f.number_field :cooktime %>
  </div>

  <div class="field">
    <%= f.label :likes %>
    <%= f.number_field :likes %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.number_field :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Recipes</h1>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Picture</th>
        <th>User_id</th>
        <th>Ingredients</th>
        <th>Description</th>
        <!-- <th>Serving</th> -->
        <th>Language</th>
        <!-- <th>Preptime</th> -->
        <!-- <th>Cooktime</th> -->
        <!-- <th>Likes</th> -->
        <th>Notes</th>
        <th>Comments</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.title %></td>
          <td><%= recipe.picture %></td>
          <td><%= recipe.user_id %></td>
          <td><%= truncate(recipe.ingredients, length: 15) { link_to "more", recipe }%></td>
          <td><%= truncate(recipe.description, length: 15) { link_to "more", recipe }%></td>
          <!-- <td><%= recipe.serving %></td> -->
          <td><%= recipe.language %></td>
          <!-- <td><%= recipe.preptime %></td> -->
          <!-- <td><%= recipe.cooktime %></td> -->
          <!-- <td><%= recipe.likes %></td> -->
          <td><%= recipe.notes %></td>
          <td><%= recipe.comments %></td>
          <td><%= link_to 'Show', recipe, class: "label label-success" %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe), class: "label label-primary" %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?'}, class: "label label-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <br>

  <%= link_to 'New Recipe', new_recipe_path, class: "label label-success" %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @recipe.picture %>
</p>

<p>
  <strong>User Id:</strong>
  <%= @recipe.user_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Serving:</strong>
  <%= @recipe.serving %>
</p>

<p>
  <strong>Language:</strong>
  <%= @recipe.language %>
</p>

<p>
  <strong>Preptime:</strong>
  <%= @recipe.preptime %>
</p>

<p>
  <strong>Cooktime:</strong>
  <%= @recipe.cooktime %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @recipe.likes %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @recipe.notes %>
</p>


<p>
  <strong>Comments:</strong>
  <%= @recipe.comments %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe), class: "label label-success" %> |
<%= link_to 'Back', recipes_path, class: "label label-warning" %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :avatar %>
    <%= f.text_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :recipes %>
    <%= f.number_field :recipes %>
  </div>

  <div class="field">
    <%= f.label :following %>
    <%= f.number_field :following %>
  </div>

  <div class="field">
    <%= f.label :followers %>
    <%= f.number_field :followers %>
  </div>

  <div class="field">
    <%= f.label :translated %>
    <%= f.text_field :translated %>
  </div>

  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>

  <div class="field">
    <%= f.label :menu %>
    <%= f.text_area :menu %>
  </div>

  <div class="field">
    <%= f.label :planner %>
    <%= f.text_area :planner %>
  </div>

  <div class="field">
    <%= f.label :shoplist %>
    <%= f.text_area :shoplist %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>All Users</h1>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <!-- <th>Email</th> -->
        <th>Language</th>
        <!-- <th>Password</th> -->
        <th>Avatar</th>
        <th>Recipes</th>
        <!-- <th>Following</th> -->
        <!-- <th>Followers</th> -->
        <th>Translated</th>
        <th>Points</th>
        <!-- <th>Menu</th> -->
        <!-- <th>Planner</th> -->
        <!-- <th>Shoplist</th> -->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <!-- <td><%= user.email %></td> -->
          <td><%= user.language %></td>
          <!-- <td><%= user.password %></td> -->
          <td><%= user.avatar %></td>
          <td><%= user.recipes.count %></td>
          <!-- <td><%= user.following %></td> -->
          <!-- <td><%= user.followers %></td> -->
          <td><%= user.translated %></td>
          <td><%= user.points %></td>
          <!-- <td><%= user.menu %></td> -->
          <!-- <td><%= user.planner %></td> -->
          <!-- <td><%= user.shoplist %></td> -->
          <td><%= link_to 'Show', user, class: "label label-success" %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: "label label-primary" %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <br>

  <%= link_to 'New User', new_user_path, class: "label label-success" %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
      <p id="notice"><%= notice %></p>

      <h1><%= @user.name %>'s Profile:</h1>

      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>

      <p>
        <strong>Language:</strong>
        <%= @user.language %>
      </p>

      <p>
        <!-- <strong>Password:</strong> -->
        <!-- <%= @user.password %> -->
      </p>

      <!-- <p>
        <strong>Avatar:</strong>
        <%= @user.avatar %>
      </p> -->

      <p>
        <strong>Recipes:</strong>
        <%= @user.recipes.count %>
      </p>

      <p>
        <strong>Following:</strong>
        <%= @user.following %>
      </p>

      <p>
        <strong>Followers:</strong>
        <%= @user.followers %>
      </p>

      <p>
        <strong>Translated:</strong>
        <%= @user.translated %>
      </p>

      <p>
        <strong>Points:</strong>
        <%= @user.points %>
      </p>

      <p>
        <strong>Menu:</strong>
        <%= @user.menu %>
      </p>

      <p>
        <strong>Planner:</strong>
        <%= @user.planner %>
      </p>

      <p>
        <strong>Shoplist:</strong>
        <%= @user.shoplist %>
      </p>

      <%= link_to 'Edit', edit_user_path(@user), class: "label label-success" %> |
      <%= link_to 'Back', users_path, class: "label label-warning" %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>